name: sc_project_generator
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.19.4 <3.0.0'

# This package supports all platforms listed below.
platforms:
  linux:
  macos:
  windows:
  
# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
dependencies:
  dcli: ^1.36.0
  uuid: ^3.0.7
  yaml: ^3.1.1
  # tint: ^2.0.1
