structures:
  - root:
      - src
      - dist

  - root:
      - REMOVE:
        - test
        - second test
        - meep:
          - ralp:
            - moop
            - meee
            - meee
          - rollo
  
  - root:
      - src:
        - twee
        - javascript
        - css
      - dist:
        - assets:
          - test please remove

directory-names:
  src: src
  dist: dist
  